// src/app/layout.tsx:1
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import "./styles/globals.css";
import "./globals.css";
import { ClientThemeProvider } from "@/components/ClientThemeProvider";
import { SessionProvider } from "@/components/SessionProvider";
import React from "react";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        {/*<ClientThemeProvider>{children}</ClientThemeProvider>*/}
        <SessionProvider>
          <ClientThemeProvider>
            {children}
            <Toaster />
          </ClientThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
